kind: Service
apiVersion: v1
metadata:
  name: basic-service-service
spec:
  type: LoadBalancer
  selector:
    app: basic-service
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080